### ISSUE TITLE
Adding a term in set editor is hard when there are a lot of terms

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#129]
**Is your feature request related to a problem? Please describe.**
When there are many terms in a set, you have to scroll to the top and back down to add a term, because the add/import terms buttons are at the top

**Describe the solution you'd like**
Make the header for add/import terms position sticky
```scss
#home > form > h2:first-of-child {
  position: sticky;
  top: 120px;
  padding: 1rem 0;
  z-index: 1;
  background-color: white;
}
```

**Describe alternatives you've considered**
Put the add/import terms stuff on the side rather than the top

**Additional context**
Even harder on small screens
